; PlatformIO Project Configuration File

[env]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 9600
build_flags = -std=gnu++17
lib_deps =
    paulstoffregen/OneWire @ ^2.3.8
    milesburton/DallasTemperature @ ^3.9.1

[env:set]
build_src_filter = +<set.cpp>

[env:oya]
build_src_filter = +<function.cpp> +<oya.cpp>

[env:koki]
build_src_filter = +<function.cpp> +<koki.cpp>
